dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "7"
env:
    - EMBER_VERSION=default
    - EMBER_VERSION=release
    - EMBER_VERSION=beta
    - EMBER_VERSION=canary
jobs:
  fast_finish: true
  allow_failures:
    - env: EMBER_VERSION=release
    - env: EMBER_VERSION=beta
    - env: EMBER_VERSION=canary

before_install:
    # setting the path for phantom.js 2.0.0
    - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
    # starting a GUI to run tests, per https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-to-run-tests-that-require-a-gui
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - "npm config set spin false"
    - "npm install -g npm@^2"
install:
    - mkdir travis-phantomjs
    - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
    - tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs
    - export PATH=$PWD/travis-phantomjs:$PATH
    - npm install -g bower
    - npm install
    - bower install
script:
    - ember test --server

# language: node_js
# node_js:
#   - 7
# cache:
#    npm: false
# # npm test
# make test

# before_install:
#   - npm i -g npm@version-number
#   - npm i -g npm@version-number
#   - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
#   - export PATH="$HOME/.yarn/bin:$PATH"
# before_script:
#   - npm install -g gulp-cli
# script: gulp




# language: node_js
# node_js:
#   - 4.2
# before_script:
#   - npm install -g bower
#   - bower install


# language: node_js
# node_js:
#   - 'stable'
# install: npm install
# services:
#   - postgresql
# before_script:
#   - psql -c 'create database test_db;' -U postgres
# script: npm test
# after_success: npm run coverage

# language: node_js
# node_js:
#   - 11.6.0
# cache: yarn

# install: 
#   - yarn install

# script: 
#   - yarn test
#   - yarn run build

# deploy: 
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN
#   local_dir: build
#   on:
#     branch: master



# language: node_js
# node_js:
#   - "8"
# cache: yarn
# jobs:
#   include:
#     - stage: test
#       script:
#         - echo 'Deploy!!'
#         - echo 'Installing Deps!'
#         - yarn
#         - echo 'Testing!'
#         - yarn test:prod
#     - stage: deploy
#       # script:
#       #   - npm install -g firebase-tools
#       #   - yarn build
#       #   - firebase deploy --token "$FIREBASE_TOKEN"
# stages:
#   - name: test
#     # require the type to be a PR
#     if: type = pull_request
#   - name: deploy
#     # require the type to be push to master
#     if: type = push AND branch = master

# language: android
# jdk: oraclejdk8

# components:
#   - tools
#   - tools
#   - platform-tools
#   - extra-google-google_play_services
#   - extra-google-m2repository
#   - extra-android-m2repository
#   - build-tools-25.0.0
#   - android-22
#   # - sys-img-armeabi-v7a-android-22

# before_install:
#   - yes | sdkmanager "platforms;android-27"
#   - yes | sdkmanager "platforms;android-28"

# before_script:
#   - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
#   - emulator -avd test -no-audio -no-window &
#   - android-wait-for-emulator
#   - adb shell input keyevent 82 &

# script: 
#   - ./gradlew assembleDebug
#   - echo "Travis branch is $TRAVIS_BRANCH"
#   - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"



